### ISSUE TITLE
Borrar preferencia

### ISSUE THREAD

**Issue by litlplastkastl** [JaquerEspeis/codigo-de-conducta#1]
Buenas, seria bueno borrar el tema de preferencia cuando se relaciona con la orientation sexual. Preferencia hace allusion de que se elige la orientation sexual y este no es el caso. Ademas es una terminología que utiliza las personas que están en contra de los derechos humanos como los fundamentalistas religiosos.

**Comment by dtec83** [comment]
Muchas gracias Michelle :)
